# Generated by Django 5.2.4 on 2025-08-08 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_email', models.EmailField(max_length=254)),
                ('mother_email', models.EmailField(max_length=254)),
                ('father_phone', models.CharField(max_length=10)),
                ('mother_phone', models.CharField(max_length=10)),
                ('father_age', models.PositiveIntegerField(blank=True, null=True)),
                ('mother_age', models.PositiveIntegerField()),
                ('father_aadhar', models.CharField(max_length=12)),
                ('mother_aadhar', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('reason', models.TextField()),
                ('document', models.FileField(upload_to='documents/')),
                ('is_approved', models.BooleanField(default=False)),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
