# Generated by Django 5.2.4 on 2025-08-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adoptionapplication_delete_adoptionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='children/')),
                ('health', models.TextField()),
                ('background', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.child'),
        ),
    ]
