# Generated by Django 5.2.4 on 2025-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_child_adoptionapplication_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mother_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
