# Generated by Django 5.2.4 on 2025-08-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_registration_mother_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Adopted', 'Adopted')], default='Available', max_length=20),
        ),
    ]
